from selenium import webdriver
import time
import pyautogui
driver=webdriver.Chrome()
def parse_years(company):
    driver.get('https://ru.tradingview.com')
    pyautogui.FAILSAFE = False
    button_1=driver.find_elements_by_class_name("searchText-3MXIiLE-")
    button_1[0].click()
    time.sleep(2)
    texting=driver.find_elements_by_xpath("/html/body/div[6]/div/div/div[2]/div/div/div[1]/div/div[1]/span/form/input")
    time.sleep(2)
    texting[0].send_keys(company)
    time.sleep(2)
    choosing=driver.find_elements_by_xpath("/html/body/div[6]/div/div/div[2]/div/div/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div[1]/div[2]/div[1]")
    choosing[0].click()
    time.sleep(2)
    action = webdriver.ActionChains(driver)
    action.move_by_offset(500,200).perform()
    time.sleep(2)
    pyautogui.scroll(clicks = 1)
    time.sleep(2)
    more_date=driver.find_elements_by_xpath("/html/body/div[2]/div[5]/div/div[1]/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[12]/button")
    more_date[0].click()
    time.sleep(2)
    statistics=driver.find_elements_by_xpath("/html/body/div[6]/div/div/div[1]/div/div[2]/div/div[1]/div[1]/div/span[5]/span")
    statistics[0].click()
    time.sleep(2)
    pyautogui.moveTo(510, 340)
    time.sleep(2)
    pyautogui.click(button='right')
    time.sleep(2)
    pyautogui.click(550, 470)
    time.sleep(2)
    pyautogui.moveTo(0, 0)
    time.sleep(2)
    pyautogui.press('enter')
    time.sleep(80)
    pyautogui.moveTo(0,0)



def parse_quarters(company):
    driver.get('https://ru.tradingview.com')
    button_1=driver.find_elements_by_class_name("searchText-3MXIiLE-")
    button_1[0].click()
    time.sleep(2)
    texting=driver.find_elements_by_xpath("/html/body/div[6]/div/div/div[2]/div/div/div[1]/div/div[1]/span/form/input")
    texting[0].send_keys(company)
    time.sleep(2)
    choosing=driver.find_elements_by_xpath("/html/body/div[6]/div/div/div[2]/div/div/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div[1]/div[2]/div[1]")
    choosing[0].click()
    time.sleep(2)
    action = webdriver.ActionChains(driver)
    action.move_by_offset(100,20).perform()
    time.sleep(2)
    more_date=driver.find_elements_by_xpath("/html/body/div[2]/div[5]/div/div[1]/div[1]/div[1]/div[2]/div[2]/div/div[2]/div[12]/button")
    more_date[0].click()
    time.sleep(2)
    statistics=driver.find_elements_by_xpath("/html/body/div[6]/div/div/div[1]/div/div[2]/div/div[1]/div[1]/div/span[5]/span")
    statistics[0].click()
    time.sleep(2)
    statistics_quarter=driver.find_elements_by_xpath("//html/body/div[6]/div/div/div[1]/div/div[2]/div/div[1]/div[2]/div/div/div/div/button[2]")
    statistics_quarter[0].click()
    time.sleep(2)
    pyautogui.moveTo(510, 340)
    time.sleep(2)
    pyautogui.click(button='right')
    time.sleep(2)
    pyautogui.click(550, 470)
    time.sleep(2)
    pyautogui.moveTo(0, 0)
    time.sleep(2)
    pyautogui.press('enter')
    time.sleep(80)
    pyautogui.moveTo(0,0)

companies = ['gazp', 'sber', 'vtbr','gmkn','poly','yndx','lkoh','alrs','nlmk','rosn','chmf','magn','afks','rual','five','nvtk','tatn','mgnt','mail','mtss','irao','dsky','plzl','moex','aflt','phor','ozon','tcsg','pikk','sngsp','mtlr','sberp','mvid','sgzh','pogr','sngs','tatnp','sibn','fees','fxcn','hydr','rasp','agro','belu','upro','banep','rsti','enpg','qiwi']
for i in [companies[28], companies[30]]:
    parse_years(i)
