# Generated by Django 3.2.9 on 2021-11-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_params',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_cashflow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_book_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_ebidta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
