# Generated by Django 3.2.9 on 2021-12-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_params_full',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_0', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_6', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_7', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_8', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_9', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_10', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_11', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_12', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_13', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_14', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_15', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_16', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_17', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_18', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_19', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_21', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_22', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_23', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_24', models.DecimalField(decimal_places=2, max_digits=10)),
                ('a_25', models.CharField(max_length=10)),
                ('a_26', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='stock_price',
            new_name='stock_price_full',
        ),
        migrations.DeleteModel(
            name='stock_params',
        ),
    ]
