from django.db import models

class stock_params_full(models.Model):
 id = models.IntegerField(primary_key=True)
 a_0 = models.DecimalField(max_digits=10, decimal_places=2)
 a_1 = models.DecimalField(max_digits=10, decimal_places=2)
 a_2 = models.DecimalField(max_digits=10, decimal_places=2)
 a_3 = models.DecimalField(max_digits=10, decimal_places=2)
 a_4 = models.DecimalField(max_digits=10, decimal_places=2)
 a_5 = models.DecimalField(max_digits=10, decimal_places=2)
 a_6 = models.DecimalField(max_digits=10, decimal_places=2)
 a_7 = models.DecimalField(max_digits=10, decimal_places=2)
 a_8 = models.DecimalField(max_digits=10, decimal_places=2)
 a_9 = models.DecimalField(max_digits=10, decimal_places=2)
 a_10 = models.DecimalField(max_digits=10, decimal_places=2)
 a_11 = models.DecimalField(max_digits=10, decimal_places=2)
 a_12 = models.DecimalField(max_digits=10, decimal_places=2)
 a_13 = models.DecimalField(max_digits=10, decimal_places=2)
 a_14 = models.DecimalField(max_digits=10, decimal_places=2)
 a_15 = models.DecimalField(max_digits=10, decimal_places=2)
 a_16 = models.DecimalField(max_digits=10, decimal_places=2)
 a_17 = models.DecimalField(max_digits=10, decimal_places=2)
 a_18 = models.DecimalField(max_digits=10, decimal_places=2)
 a_19 = models.DecimalField(max_digits=10, decimal_places=2)
 a_20 = models.DecimalField(max_digits=10, decimal_places=2)
 a_21 = models.DecimalField(max_digits=10, decimal_places=2)
 a_22 = models.DecimalField(max_digits=10, decimal_places=2)
 a_23 = models.DecimalField(max_digits=10, decimal_places=2)
 a_24= models.DecimalField(max_digits=10, decimal_places=2)
 a_25 = models.CharField(max_length=10)
 a_26 = models.DecimalField(max_digits=10, decimal_places=2)

class stock_price_full(models.Model):
 name = models.CharField(max_length=10)
 stock_price = models.DecimalField(max_digits=10, decimal_places=2)
